### ISSUE TITLE
ivy-read: Wrong type argument: symbolp, "Completion conflict history"

### ISSUE THREAD

**Issue by dalanicolai** [ibizaman/emacs-conflict#2]
The unquoted symbol `emacs-conflict--conflict-history` in the function `emacs-conflict--pick-a-conflict` causes errors in Spacemacs when using Helm or Ivy. Quoting the symbol solves the error when using Ivy, but not when using Helm. Removing the symbol fixes functionality for both Ivy and Helm.
As it appears that this symbol does not add functionality, it might be better to just remove it.

**Comment by stephsamson** [comment]
I can confirm that this is also an issue in doom.

**Comment by felixwiemuth** [comment]
In Spacemacs with helm, I'm getting the same as @stephsamson. Removing the `emacs-conflict--conflict-history` in `emacs-conflict--pick-a-conflict` also works for me.

**Comment by ibizaman** [comment]
Thanks all for the report. I don’t have much time to fix this these days but I’ll get to it eventually. In the meantime I’m happy to accept a PR. :)

**Comment by ibizaman** [comment]
I'm using ivy and this fixes the issue. Can anyone check it by checking out the branch?

The easiest way is changing the branch here:
```elisp
(use-package emacs-conflict
  :straight (emacs-conflict :type git :host github :repo "ibizaman/emacs-conflict" :branch "fix_wrongtypeargument"))
```
Then you will need to evaluate the following elisp code to clear the variable:
```elisp
(setq emacs-conflict--conflict-history nil)
```

**Comment by ibizaman** [comment]
I went on and merged the PR to avoid keeping this issue ope for too long. Feel free to reopen if there are issues with it.

**Comment by felixwiemuth** [comment]
Thank you! I updated to current the master (f4b83583115606fd9dc74c6b6faaf82100a887d2) and the basic `emacs-conflict-resolve-conflicts` works now without problems.
